---
# title: 'Seminários sobre aplicações de aprendizado descritivo -- 2025.1'
page-layout: full
---

# Introdução

Os seminários da disciplina consistem em uma apresentação coletiva (da turma) de um artigo mais recente sobre tópicos diretamente relacionados ao conteúdo visto em sala. A ideia é que a turma como um todo estude os artigos mais recentes da área e discuta esses trabalhos em sala. Em cada sessão, discutimos dois artigos recentes relacionados aos tópicos abordados nas aulas teóricas.

Para isso, adotamos um formato adaptado da proposta apresentada pelos Profs. Alec Jacobson e Colin Raffel, ambos da Universidade de Toronto (Canadá) -- veja [aqui][URL_Seminário] a proposta original. A proposta consiste em fazer uma encenação de papéis (role play) científicos para a apresentação do seminário. Nessa proposta, cada grupo cumprirá um papel na apresentação. Ao final, uma apresentação em formato de slides e um documento textual são produzidos. A apresentação é usada em sala de aula para fomentar as discussões, enquanto o documento fornece uma descrição textual das impressões da turma com a intenção de descrever o tema do artigo para um público  amplo interessado em aprendizado de máquina e mineração de dados.

São apresentados a seguir os artigos discutidos no semestre 2025/1, com os respectivos links para os slides e documentos textuais apresentando os artigos.

## [Artigo 5][Seminario_Art5]

- [Modeling Match Performance in Elite Volleyball Players: Importance of Jump Load and Strength Training Characteristics][Seminario_Art5]
- **Autores:** A.-W. de Leeuw, R. van Baar, A. Knobbe, and S. van der Zwaard. 2022
- **DOI:** [10.3390/s22207996][DOI_Art5]

## [Artigo 6][Seminario_Art6]

- [Exceptional Subitizing Patterns: Exploring Mathematical Abilities of Finnish Primary School Children with Piecewise Linear Regression][Seminario_Art6]
- **Autores:** R. M. Schouten, W. Duivesteijn, P. Räsänen, J. M. Paul, and M. Pechenizkiy. 2024
- **DOI:** [10.1007/978-3-031-70381-2_5][DOI_Art6]

<!-- URLs -->

[URL_Seminário]: https://colinraffel.com/blog/role-playing-seminar.html

[DOI_Art5]: https://doi.org/10.3390/s22207996
[DOI_Art6]: https://doi.org/10.1007/978-3-031-70381-2_5

[Seminario_Art5]: seminario3/artigo5.qmd
[Seminario_Art6]: seminario3/artigo6.qmd
